### ISSUE TITLE
Update gateway endpoints

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-service#1004]
### Description

Update the gateway to retrieve data from the right endpoints. 

Example: `core.*` -> `statistics.*`

Pay attention to renamed services.

### Acceptance Criteria

- API version 2 endpoints are up-to-date
- Integration tests pass

**Comment by nagdahimanshu** [comment]
This issue is already addressed as a part of the issues: https://github.com/LiskHQ/lisk-service/issues/996, https://github.com/LiskHQ/lisk-service/issues/998 & https://github.com/LiskHQ/lisk-service/issues/999. Hence, closing the issue.
