### ISSUE TITLE
Automate transaction processor resolution for registered modules in blockchain-indexer

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-service#1005]
### Description

Create an interface/standard that can be used for further development and implemented by future module implementations.
Add generic module support.

Make sure it covers all needs for the features offered by modules: blockchain constants, transactions, and events.

### Acceptance Criteria

- The interface is ready and reviewed by all team members
- The interface is drafted and can be used by other modules automatically without requiring any further changes to the implementation
- It allows easily adding new transaction processing logic to the application to the support all transactions supported by the modules

**Comment by MichalTuleja** [comment]
There are several updates to the issue:

- The connector works on generic schemas and does not require any custom code as of now.
- The issue should focus on indexing and preparing the abstraction layer for custom logic from the indexer perspective.
- A simple interface was proposed during the meeting.

```
interface TransactionParser {
	private const moduleId
	private const assetId

	construct()

	processTransaction(trx) {
	}

	private _updateAccount()
}
```
