### ISSUE TITLE
Migrate transaction statistics to Redis

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-service#1010]
### Description

Replace the data store for statistics to Redis using ZADD/ZRANGE.

### Acceptance Criteria

- Data is stored in Redis
- Functional tests are up-to-date

**Comment by sameersubudhi** [comment]
This issue takes low priority but might be considered for improvements post the beta release.

**Comment by sameersubudhi** [comment]
Not doing it. Hence, closing the issue.
