### ISSUE TITLE
Evaluate and improve the abstract class

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-service#1011]
### Description

Once the `alpha.1` is released there are several design aspects that need a review and potential improvements. Make a list of them and evaluate them by adding them to this issue. Create additional issues if the changes require more effort.

### Acceptance Criteria

- List of potential improvements is created
- Issues are well described with potential solutions
- Tests are updated

**Comment by sameersubudhi** [comment]
This issue will be re-evaluated post the completion of all the blockers.

**Comment by sameersubudhi** [comment]
Not necessary. Closing the issue.
