### ISSUE TITLE
Add documentation for Lisk Service

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-service#1012]
### Description

The documentation content specific to Lisk Service should be added to the `lisk-service` repository under the `docs/` folder.

### Motivation

Because the content is closely connected and it improves overall management of the Lisk documentation as a whole.

### Acceptance Criteria

- Documentation is up-to-date
- Documentation is programmatically generated
- Documentation can be rendered on the official website straight from the repo

### Additional Information

Epic: https://github.com/LiskHQ/lisk-docs/issues/1293

**Comment by sameersubudhi** [comment]
The documentation will be addressed after the initial alpha is tagged so that we already have the API properly-defined and all the necessary information is in-place. This would ensure that we do not need re-work on the documentation.

**Comment by ManuGowda** [comment]
This issue is a duplicate https://github.com/LiskHQ/lisk-service/issues/1012

**Comment by ManuGowda** [comment]
https://github.com/LiskHQ/lisk-service/issues/1012
