### ISSUE TITLE
Blockchain Connector: Add unit tests

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#1021]
### Description

Create unit tests for the following functions:

- RPC list generator
- Custom data transformations
  - Helper functions: schema-based decoder/encoder

### Acceptance Criteria

- Test are written and running with Jest

**Comment by sameersubudhi** [comment]
The test cases need to be part of the functional test suite and will be handled in https://github.com/LiskHQ/lisk-service/issues/1022

**Comment by sameersubudhi** [comment]
This issue is not required anymore. Closing it.
