### ISSUE TITLE
Blockchain Indexer: Allow calculating aggregated issues from the index

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#1025]
### Description

Allow calculating aggregated values from the index to verify the aggregated values stored in the database.

These methods should not replace the original logic.

### Acceptance Criteria

- Aggregate methods are exported for the blockchain coordinator.
- These methods should not be enabled on production by default.

**Comment by sameersubudhi** [comment]
This issue would be considered for future improvements post the beta release.
