### ISSUE TITLE
Improve reconnect capability

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#1026]
### Actual behavior

The SDK API client is able to reconnect correctly only under certain circumstances. Usually when the core application quits and starts again.

Other scenarios are not covered properly.

- For some reason the blockchain events are subscribed multiple times. That results with multiple index updates with the same data. Aggregated results can become incorrect due to that issue.
- Sometimes the indexing process does not response properly, i.e. it gets stuck and disconnects from the gateway as well. The leaves the application in an undefined state and it cannot deliver data to clients. Only manual restarts help.

The consequences of that issue is Lisk Service not able to retrieve any blockchain data (blocks, transactions, etc.).

It is also not possible to login to the wallet when this issue happens.

### Expected behavior

The issues described above are mitigated, keeping the process work as designed.

### Steps to reproduce

1. Run the app in Docker against mainnet.
2. Wait ~24hrs.
3. The process will run into the undefined state.

### Which version(s) does this affect? (Environment, OS, etc...)

`0.6.2`

**Comment by sameersubudhi** [comment]
This has been resolved with #1009. Closing the issue.
