### ISSUE TITLE
Implement dynamic decoding for events and endpoints

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-service#1097]
### Description

Add support to decode the event payloads and endpoint responses on-the-fly based on the blockchain application metadata.

### Acceptance Criteria

- The autoDecoder implementation is in-place
- Event processor should be able to automatically determine the correct schema and invoke to autoDecoder
- The endpoint proxy processor should be able to automatically determine the correct schema corresponding to the queried endpoint and invoke to autoDecoder
- Refactor current events implementation to generic implementation and avoid any hardcoding
- Handle new transaction event
- Unit tests are implemented
- Integration tests are implemented

**Comment by sameersubudhi** [comment]
This issue is now unnecessary since the api-client will now return the response in JSON format: https://github.com/LiskHQ/lisk-sdk/issues/7189.
