### ISSUE TITLE
Allow SDK endpoint proxy

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-service#1098]
### Description

Allow users to query all the available endpoints on the SDK-based blockchain application in case of a missing endpoint and return responses in the decoded format.

### Acceptance Criteria

- The following endpoints are available
- The responses are dynamically decoded as per the corresponding schema
- Integration tests are implemented

#### Endpoints
**HTTP**:  `POST /invoke`
**RPC**:    `post.invoke`

#### Request query params
Parameter | Type | Validation | Default | Comment
-- | -- | -- | -- | --
endpoint | String | | (empty) | Required
params | Object | | (empty) | Optional

**Comment by sameersubudhi** [comment]
This issue is invalid since the api-client now sends responses in the decoded JSON format. Ref: https://github.com/LiskHQ/lisk-sdk/issues/7189
