### ISSUE TITLE
Aggregate does not match

### ISSUE THREAD

**Issue by lisknonanika** [LiskHQ/lisk-service#1143]
### Actual behavior
sentVotes in `accounts` do not match `votes_received`.

`accounts`
https://mainnet-service.lisk.com/api/v2/accounts?address=lsk3h9d58ck8wwtyeamgo3e7twcswy8ymsq6r5ake

`votes_received`
https://mainnet-service.lisk.com/api/v2/votes_received?address=lsk5tyhc6tw76ybwwzt9vcefy3gryjvprkcj329tw&aggregate=true&limit=10&offset=0

### Expected behavior
Should match

### Steps to reproduce
Access each API

### Which version(s) does this affect? (Environment, OS, etc...)
v0.6.3

**Comment by sameersubudhi** [comment]
Closing the issue. Will be addressed in the v3 API instead. Ref: https://github.com/LiskHQ/lisk-service/issues/1673
