### ISSUE TITLE
Use the default npm registry for `service/core` instead of the private Lisk registry

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/lisk-service#122]
Use the default npm registry for `service/core` instead of the private Lisk registry
  - Remove the `registry` entry from `lisk-service/services/core/.npmrc`
  - Revert the corresponding change in `lisk-service/services/core/Dockerfile`

**Comment by MichalTuleja** [comment]
`lisk-elements` alpha versions are not public version and thus using them requires a different npm registry.
This will be fixed once a stable version of `lisk-elements` is released.
