### ISSUE TITLE
Replace networkID with chainID

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/lisk-service#1220]
### Description

Lisk SDK v6.0.0-alpha.3 replaces the `networkID` with `chainID`. Lisk Service internally uses `networkID` internally for multiple purposes, such as network resolution. So, the code base now must be refactored to use the `chainID` instead.

### Acceptance Criteria

- Genesis block when downloaded from the server must now be stored like `./data/${chainID}/genesis_block.json` instead of `./data/${networkIdentifier}/genesis_block.json`
- The response structure for the following endpoints are up-to-date:
  - `/api/v3/network/status`
  - `/api/v3/peers`
  - `/api/status`
- `networkIdentifier` or `networkID` is used nowhere within the code base anymore for the `/v3` API and replaced with `chainID` instead
- `transaction-statistics` uses `chainID` to resolve the network (eg: mainnet, testnet, betanet etc.) [Search for `config.serviceURL`]
- Swagger is up-to-date
- Tests are up-to-date

**Comment by ManuGowda** [comment]
With the latest research updates, we no longer require networkID as we are going to use chainID as global unique identifier across ecosystem and networks. e.g chainID "NETWORK_PREFIX:01", "Mainnet_01"

**Comment by ManuGowda** [comment]
@sameersubudhi @nagdahimanshu this is invalid now as networkID is removed and we use chainID? if this issue is invalid now lets close it? but before that please make sure we do not use networkID anywhere in code and if we still use networkID we should replace it with chainID.

**Comment by sameersubudhi** [comment]
@ManuGowda I'll update the issue and communicate with @nagdahimanshu for any further changes.
