### ISSUE TITLE
Incorrect delegate consecutiveMissedBlocks count

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/lisk-service#1387]
### Actual behavior
The `consecutiveMissedBlocks` for the following delegates are shown incorrectly:

https://service.lisk.com/api/v2/accounts?username=condor
https://service.lisk.com/api/v2/accounts?username=coinc

### Expected behavior

The `consecutiveMissedBlocks` for all the delegates must be shown correctly.

### Steps to reproduce
Check the response for the above delegates on Lisk Service (https://service.lisk.com/api/v2/accounts?username=<username>) and on Lisk Core (https://mainnet.lisk.com/api/accounts/<hexAddress>).

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Service `v0.6.4`

**Comment by przemerr** [comment]
I'm adding additional delegate https://service.lisk.com/api/v2/accounts?username=savetheworld because delegates can go back to being online resetting the count. This one should stick indefinitely since he's on a verge of a ban.

**Comment by przemerr** [comment]
If you compare https://service.lisk.com/api/v2/accounts?username=savetheworld with https://mainnet.lisk.com/api/accounts/0b987a9b1b3b106ba709deb5f88290f9b200a866
not only `consecutiveMissedBlocks` are wrong but also the `isBanned` flag, the delegate got banned recently (few hours ago).
