### ISSUE TITLE
Update newsfeed microservice

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/lisk-service#1444]
### Description

Update `newsfeed` microservice to support Strapi and Twitter v2 API to fetch Lisk's latest blogposts and tweets respectively.

### Motivation

- Migration of Lisk blog from Drupal to Strapi
- Deprecation of Twitter v1 API

### Tasks

- [ ] TODO

**Comment by sreenath-tm** [comment]
Hi I would like to contribute to this issue can you let me know how I can go about solving this issue.

**Comment by sameersubudhi** [comment]
> Hi I would like to contribute to this issue can you let me know how I can go about solving this issue.

Hi @sreenath-tm, Thank you for your interest. We have not planned any tasks for this epic yet but will be happy to accept your contributions for other open tasks.

**Comment by ManuGowda** [comment]
Closing this epic, read more here https://github.com/LiskHQ/lisk-service/issues/1540
