### ISSUE TITLE
`search` parameter throws an error in Lisk Service APIs

### ISSUE THREAD

**Issue by TalhaMaliktz** [LiskHQ/lisk-service#1679]
### Actual behavior
![image](https://github.com/LiskHQ/lisk-service/assets/13951043/d6fd6306-792e-40dc-ab58-d84d06ce7b6e)

The API returns the expected result if the request is made with another parameter such as `name`.
### Expected behavior
The query should return a staker based on the search query.

The issue with the `search` keyword is also present in other APIs so might need to check the relevant APIs as well.

### Steps to reproduce
query `/pos/staker?search=stellardynamic`

### Which version(s) does this affect? (Environment, OS, etc...)
`lisk-service v3`

**Comment by vardan10** [comment]
As the error suggests we need one of address, public key or name to be specified.

**Comment by sameersubudhi** [comment]
@TalhaMaliktz The `search` keyword is used to filter the results from the endpoint.

Let's consider the `/pos/stakes` endpoint:
- It let's you query all the outgoing stakes from the specified staker identified by their `address`, `publicKey` or `name`
- With the `search` param you can filter the results (outgoing stakes for the above staker) by a validator's (stake receiver) `address`, `publicKey` or `name`

We can connect offline if you need any further clarification.
