### ISSUE TITLE
Create abstraction layer for blockchain index

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#207]
### Description

Create abstraction layer for blockchain index based on the experimental PouchDB implementation.

Consider the following backends that might be used in the future:

- Redis
- RediSearch
- PostgreSQL
- SQlite
- MongoDB

### Motivation

- Need to know the technical limitations of storing blockchain data index

### Acceptance Criteria

- Comments in the issue with results
- Draft implementation for Redis

**Comment by nagdahimanshu** [comment]
Reason to not proceed with Redis secondary index:

- Secondary index uses a score to create index. Refer ZADD method.
   We intended to directly use the prospective indexed attributes as the score. Hence, indexing non-numeric data such as address, publicKey, username, ip etc. though feasible is a cumbersome process. It would introduce unnecessary computational overhead for (de-)encoding.
