### ISSUE TITLE
Fix address search

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#232]
### Actual behavior

The API endpoint `/search` does not work with an address.

### Expected behavior

The API endpoint `/search` does works with an address.

### Steps to reproduce

Request `https://betanet-service.lisk.io/api/v1/search?q=6037832807575997134L`

### Which version(s) does this affect? (Environment, OS, etc...)

`0.2.0-beta.1`

**Comment by nagdahimanshu** [comment]
This bug does not exists anymore.
