### ISSUE TITLE
Update vote index on block arrival

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#256]
### Description

Each block that contains voting transactions requires account voting status to be updated in the vote database.
Affected accounts require indexing and re-indexing on status change.

Use `app:getAccount` to retrieve votes for all affected accounts.

### Motivation

- To make possible the vote search, accounts need to be updated on each recent block

### Acceptance Criteria

- Voting index gets updated on each block update

**Comment by sameersubudhi** [comment]
Closing the issue. The feature has already been developed as a part of PR #332.
