### ISSUE TITLE
Enable transaction broadcast

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#259]
### Description

Make it possible to broadcast transactions using Lisk Service as a proxy.

Use `app:postTransaction` method to broadcast an encoded transaction.

Make sure so the client gets instant response from the peer.

### Motivation

- This feature is required by the UI clients

### Acceptance Criteria

- Transaction broadcast is possible
- Gateway is updated with the API version 2

#### Endpoints

- HTTP POST `/api/v2/transactions​`
- RPC `post.transactions`

#### Request parameters

No params required.

Payload:

```jsonc
{"transaction":"08021000180d2080c2d72f2a200fe9a3f1a21b5530f27f87a414b549e79a940bf24fdf2b2f05e7f22aeeecc86a32270880c2d72f12144fd8cc4e27a3489b57ed986efe3d327d3de40d921a0a73656e6420746f6b656e3a4069242925e0e377906364fe6c2eed67f419dfc1a757f73e848ff2f1ff97477f90263487d20aedf538edffe2ce5b3e7601a8528e5cd63845272e9d79c294a6590a"}
```

#### Response example

200 OK

```jsonc
{
  "message": "Transaction payload was successfully passed to the network node"
  "transactionId": "123456789"
}
```

400 Bad Request
```jsonc
{
  "error": true,
  "message": "Transaction payload was rejected by the network node"
}

```

500 Internal Server Error
```jsonc
{
  "error": true,
  "message": "Unable to reach a network node"
}

```

**Comment by sameersubudhi** [comment]
Hi @MichalTuleja,

I reckon we require to update the issue description such that the binary payload is passed in the POST request body as a JSON object in the following format. The recommended format is consistent with the result generated by `transaction:create` method, which the user uses to create and sign a transaction. What are your thoughts?

```
{"transaction":"08021000180d2080c2d72f2a200fe9a3f1a21b5530f27f87a414b549e79a940bf24fdf2b2f05e7f22aeeecc86a32270880c2d72f12144fd8cc4e27a3489b57ed986efe3d327d3de40d921a0a73656e6420746f6b656e3a4069242925e0e377906364fe6c2eed67f419dfc1a757f73e848ff2f1ff97477f90263487d20aedf538edffe2ce5b3e7601a8528e5cd63845272e9d79c294a6590a"}
```

**Comment by MichalTuleja** [comment]
Hi @sameersubudhi, the JSON format you've suggested can be implemented. It also has a potential of extending it for additional properties which might be useful in the future.
I'll update the specs in the issue.
