### ISSUE TITLE
Fix transaction date conversion

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#274]
### Actual behavior

Timestamp returned from `/api/v1/transactions` endpoint is incorrect.

### Expected behavior

Timestamp returned from `/api/v1/transactions` endpoint is in a proper unix time format.

### Steps to reproduce

Retrieve `/api/v1/transactions`.

### Which version(s) does this affect? (Environment, OS, etc...)

`v0.2.0-beta.1`

### Additional information

Possible solution might a removal of the line

```
transaction.unixTimestamp = await coreApi.getUnixTime(transaction.timestamp)
```

from the following code:

```
			if (!transaction.timestamp) {
				const txBlock = (await getBlocks({ height: transaction.height })).data[0];
				transaction.timestamp = txBlock.unixTimestamp;
			}
			transaction.unixTimestamp = await coreApi.getUnixTime(transaction.timestamp);
			return transaction;
		},
```

**Comment by sameersubudhi** [comment]
The following change should fix the issue:
```
if (!transaction.timestamp) {
	const txBlock = (await getBlocks({ height: transaction.height })).data[0];
	transaction.unixTimestamp = txBlock.unixTimestamp;
} else {
	transaction.unixTimestamp = await coreApi.getUnixTime(transaction.timestamp);
}
```
