### ISSUE TITLE
Fix block endpoint time intervals

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#348]
### Actual behavior

The UI reported `from` and `to` parameters not working properly.

### Expected behavior

Make sure `from/to` properties work properly with unix timestamps.

### Steps to reproduce

`/blocks?from=<unixTimestamp>&to=<unixTimestamp>`

**Comment by isalga** [comment]
We concluded that the bug was on desktop side. This will be fix [here #3351](https://github.com/LiskHQ/lisk-desktop/pull/3351). Feel free to close this issue.
