### ISSUE TITLE
Don't make direct HTTP connections deprecated; Health check

### ISSUE THREAD

**Issue by adamant-al** [LiskHQ/lisk-service#377]
Hi Lisk developers!

### Description

I see image https://lisk.io/documentation/lisk-service/_images/architecture.png and I am disappointed that you call node's HTTP connections deprecated, and "Will be replaced by Lisk Service soon".

I've found Lisk Service idea wonderful, and understand it will be convenient for developers in most cases. Still I ask you to call this way of interaction "recommended", and do not call HTTP connections "deprecated" and continue to support them.

As always, there is a conflict between convenience and reliability.

### Motivation

1. Lisk Service is a step back from decentralisation to centralisation.

2. Lisk Service is a point of failure.

3. When a developer offers an app to a user, they may wish to point this app to connect to their own nodes because of different reasons. Such users have their own nodes, but having a Lisk Service is another step.

In real life, it is not possible to run a service with a 100% uptime. Servers go down, software have bugs, node can be in sync, and so on. In some countries, governments suddenly block IPs and domains. A Blockchain has advantages here—client apps may connect to any available node. Other side, it makes apps to process connection logic and do "Health check" for nodes.

It makes no sense to implement Health check in Lisk Service, as it is the point of failure itself, it is a centralised service. But have a look at implementing Health check in Lisk SDK. This will help also for Lisk Service, as connection App-Lisk Service-SDK—Blockchain becomes more reliable.

### Implementation

Here is a reference implementation of Health check: https://github.com/Adamant-im/adamant-im/blob/master/src/lib/adamant-api-client.js

It is based on `/api/node/status` of Lisk Core ~0.9, where we've added height and socket support info. It checks the list of nodes from the config, and choose which node to connect. Health check requests if node is live, of supported version, and chooses synced one. It also protects from fraud when a single node says it have the false-best height (f. e., synced height + 100), comparing height to other nodes.

### Final thoughts

When reliability comes first, it may be also a good idea to implement Health checks for other connected services like Electrum.

**Comment by MichalTuleja** [comment]
Hi @adamant-al,

Thank you for sharing your concerns with us.

To begin with, I would like to point out that Lisk Service is an open-source product that can be run by anyone and is supported by a decentralized network. So this thing did not change, Lisk is a decentralized protocol and a decentralized product. Anyone can run an own node and an own instance of Lisk Service in parallel. With that in mind, I would treat Lisk Service as a loosely-coupled extension to Lisk Core product.

It might be true that Lisk Service adds more complexity and can be another point of failure. Please take note that these features are removed from Lisk Core and thanks to this approach Lisk Core benefits better stability. These features are re-implemented in the Lisk Service application receiving more support from active developers than Lisk Core API did before that change.

Lisk Service is based on microservice architecture which makes it possible to achieve near 100% availability by running several instances at once. Support for multiple modern techniques such as Docker makes deployments and scaling it up much easier.

For mission-critical tasks such as transaction processing, it is still possible to access the Lisk node directly from a client. Lisk Service will be always optional albeit recommended part of the Lisk ecosystem.
