### ISSUE TITLE
Provide the list of latest votes

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-service#40]
### Description

As a user; I'd like to see the latest votes 

### Motivation

Help delegates have a better understanding about changes in the list of their voters.
Help voters get notified if the community is revoking trust from a delegate or increasing attention towards another.

### Acceptance Criteria

1. Should list the below information
2. Date and time 
3. Transaction details 
4. Sender id
5. Current balance
6. Round 
7. Votes

**Comment by MichalTuleja** [comment]
This feature is already implemented and discontinued. This issue can be closed.
