### ISSUE TITLE
Knex pool becomes full and it fails to stay up to date

### ISSUE THREAD

**Issue by nerdvibe** [LiskHQ/lisk-service#431]
### Actual behavior
My logs are bombarded with `knex pool full`.
`Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`
```
(node:1) UnhandledPromiseRejectionWarning: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_MySQL.acquireConnection (/home/lisk/lisk-service/core/node_modules/knex/lib/client.js:348:26)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
```

It also appears that the integrity of the blocks table is broken, since I am at height 715847 but I have 707911 rows. Also, MySQL gets stuck without updating anymore

### Steps to reproduce

Just from a fresh node. I just exposed the MySQL port on the server in order to connect for development. 

Lisk Core running via npm, Lisk Service via Docker.

### Which version(s) does this affect? (Environment, OS, etc...)

Ubuntu 18.04, on develop branch

**Comment by nagdahimanshu** [comment]
Dear @nerdvibe , Thank you for creating the issue. Our team had fixed this issue as part of the PR #[436](https://github.com/LiskHQ/lisk-service/pull/436).
