### ISSUE TITLE
Fix transaction statistics

### ISSUE THREAD

**Issue by nagdahimanshu** [LiskHQ/lisk-service#433]
### Transaction statistics are not calculated properly 

```2021-04-01T20:53:45.929 WARN [queue] transactionStatisticsQueue Job failed,TypeError: Cannot assign to read only property '0' of string 'Invalid Number'```

### Expected behavior
Stats calculated properly with no error

### Steps to reproduce
Run Lisk Service against lisk-core betanet5 and call `api/v2/transactions/statistics/day`

**Comment by corbifex** [comment]
I don't know if this is the same issue `api/v2/transactions/statistics/day` shows max 100 txs a day.

**Comment by nagdahimanshu** [comment]
> I don't know if this is the same issue `api/v2/transactions/statistics/day` shows max 100 `txs` a day.

Hi @corbifex , Thanks for pointing it out. I am fixing the issue you mentioned in the same issue.
