### ISSUE TITLE
Wrong charset for transactions table on mysql

### ISSUE THREAD

**Issue by nerdvibe** [LiskHQ/lisk-service#461]
### Actual behavior

The charset of the transactions table doesn't accept transactions with special characters. This means that [transactions like this](https://betanet.lisk.observer/transaction/6dedd5947a1d46c40d0b88b2dbdb44ab3568d2e3193d6b86a3d30c44bf412783), don't get picked up by Lisk-Core because of `ł` character.

### Expected behavior

The transactions table should store transactions that contain special chars like `ł`. In

### Steps to reproduce

Just run Lisk Service in docker with MySQL on docker. 

### Which version(s) does this affect? (Environment, OS, etc...)

commit c8360a8

### How I (temporarily) solved it?
I fixed it by replacing the default charset from `latin1` to `utf8mb4_unicode_ci `. This is the query `ALTER TABLE transactions CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`

**Comment by sameersubudhi** [comment]
Dear @nerdvibe ,

Thank you for highlighting the issue.

Our team had earlier identified and fixed this issue as part of the PR https://github.com/LiskHQ/lisk-service/pull/436 and would be made available with the next beta.
Hence, closing this issue.
