### ISSUE TITLE
Missing response from subscribe API

### ISSUE THREAD

**Issue by artenais** [LiskHQ/lisk-service#474]
Good day to everyone,

While trying to use the Subscribe API with nodejs I return no message at all? I am surely missing something so any hint will we valuable

```
var io = require('socket.io-client');
 	const connection = io.connect('https://service.lisk.io/blockchain', { transports: ['websocket'] });
	console.log( connection )
	connection.on( 'connect', () => {
		console.log("HELLO WEBSOCKET")
	})
	connection.on('update.block', ( block ) => { 
		console.log( block )
	});
```

I se the "HELLO WEBSOCKET" message, but no update block message. I am using socket.io client v 2.0.4 ( to be sure to hit compatibility, I will change it later to 2.4.0 ).

Is the api offline maybe?

Thank you for any help.

**Comment by MichalTuleja** [comment]
Hi @artenais,

thanks for reporting the issue.

The WebSocket subscribe API was only a draft concept in the Lisk Service `0.1.x` and not available at the release time.
The subscribe API will be officially supported in the upcoming release (`0.3.0`).
