### ISSUE TITLE
Fix legacy account indexing

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#475]
### Actual behavior

The `/account` endpoint does not show the legacy account details.

### Expected behavior

The `/account` endpoint shows the legacy account details.

### Steps to reproduce

https://alphanet-v5-legacy-service.liskdev.net/api/v2/accounts?publicKey=808cc3a072dde49eb6761d07c5a9bf10364b8cd0c4da52f985eac3774189e1a8

https://alphanet-v5-legacy-service.liskdev.net/api/v2/accounts?address=lskehmcfxh7vq6mpjgexe2c2ftq4gdeb5qfkoq8cm

### Which version(s) does this affect? (Environment, OS, etc...)

Alphanet `http://134.209.199.225:4000/api/node/info`

**Comment by UsamaHameed** [comment]
The issue mentions publicKey 808cc3a072dde49eb6761d07c5a9bf10364b8cd0c4da52f985eac3774189e1a8 which actually does not exist on the network. 

However, I can reproduce the issue for this account: 0fe9a3f1a21b5530f27f87a414b549e79a940bf24fdf2b2f05e7f22aeeecc86a

https://alphanet-v5-legacy-service.liskdev.net/api/v2/accounts?publicKey=0fe9a3f1a21b5530f27f87a414b549e79a940bf24fdf2b2f05e7f22aeeecc86a

It seems like this account actually does exist when queried with the address: https://alphanet-v5-legacy-service.liskdev.net/api/v2/accounts?address=lskdxc4ta5j43jp9ro3f8zqbxta9fn6jwzjucw7yt
