### ISSUE TITLE
Review integration tests

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-service#585]
### Description

Make sure integration tests are properly written and cover all API endpoints of the application.

Make sure the `Jenkinsfile` is up-to-date and runs all required tests.

### Motivation

Make sure integration tests are properly written and cover all API endpoints of the application.

### Acceptance Criteria

- Tests are present and are within its scope

**Comment by MichalTuleja** [comment]
The integration tests' are reviewed. 

There are no improvements required with a remark: all tests need to be enabled before the beta phase.
