### ISSUE TITLE
Fees are processing forever

### ISSUE THREAD

**Issue by faustbrian** [LiskHQ/lisk-service#630]
### Actual behavior

First time I checked last thursday and been getting `{"error":true,"message":"The estimates are currently under processing. Please retry in 30 seconds."}` since then, probably way before that too.

### Expected behavior

Get a response as documented at https://lisk.com/documentation/lisk-service/references/api-testnet.html#/Fee/get_fees

### Steps to reproduce

Visit https://testnet-service.lisk.io/api/v2/fees

**Comment by sameersubudhi** [comment]
Thank you for raising the issue. It has already been fixed as a part of the PR: https://github.com/LiskHQ/lisk-service/issues/625 and would be made available in the forthcoming patch release.
