### ISSUE TITLE
Return 200 OK instead of 404

### ISSUE THREAD

**Issue by adamant-al** [LiskHQ/lisk-service#698]
### Description
When requesting Lisk Core http_api and Lisk Service endpoints like `account` and `transactions` in a browser app, if a request was success, but no data available in the blockchain, Lisk Service returns `404`. I think it will be better to return `200` with the same contents, f. e. `{"errors":[{"message":"Account with address '5c8288aa46ac4104fa072498b06ace7b91b90c16' was not found"}]}`.

### Motivation
When user creates a new Lisk account, an app requests 
`/api/accounts/address_here` (Lisk Core)
or
`/api/v2/accounts?address=address_here` (Lisk Service)
 to update its balance. 
Because for new accounts it returns `404`, user's console are full of 404 errors, which misleads as errors in an application.

**Comment by MichalTuleja** [comment]
Hi @adamant-al,

Thank you for creating the issue.

According to the [specification](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) the `404 Not Found` code is used when the resource was not found - which is the case here. The `200 OK` would require a meaningful content.

That response should be handled properly by the application. Therefore the issue can be closed.
