### ISSUE TITLE
Fix wallet name

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-service#728]
This one is a **cold** wallet of Binance, not a hot wallet.

old address: 5037006598898191401L
binary Address: 290ca082d00ae7452ea577bdb5d7532b87059b12
new address: lskmpb6xzeux5tk65qm7ffs5qdtm7cu5b2rmog6tr

**Comment by sameersubudhi** [comment]
This was resolved as a part of the PR: https://github.com/LiskHQ/lisk-service/pull/695
