### ISSUE TITLE
Mitigate rank calculation issues (standby -> active)

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-service#731]
Original title: If standby delegate get vote and enters top 101 it disappears in rank list

I noticed several times when i was a standby delegate and someone voted me, the new rank was invisible on explorers.  For example: I was rank 103, got a vote and my new rank was 61. On Explorers there were only rank ...59, 60, 62, 63... - rank 61 missing. Developers of Liskscan said this is an issue with Lisk Service and should be fixed.

**Comment by sameersubudhi** [comment]
@punkrock Thank you for the update. While we're checking on the issue to get the changes reflected immediately, please be notified that this should be resolved automatically every time the complete delegates list is refreshed, which is every 5 minutes.
