### ISSUE TITLE
Fix transaction retrieval by public key (tests)

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#736]
### Actual behavior

Jenkins fails on public key retrieval.

### Expected behavior

Fix transaction retrieval by a public key feature or tests. 

It is failing on Jenkins and has been temporarily disabled.

### Steps to reproduce

Run Jenkins tests

### Which version(s) does this affect? (Environment, OS, etc...)

0.4.4

### Additional information

```
Summary of all failing tests

FAIL integration/api_v2/http/transactions.test.js
  ● Transactions API › Retrieve transaction list by sender public key › existing sender public key -> ok

    Status code: 400
    			
    {
      "error": true,
      "message": "Invalid input: The 'senderPublicKey' field length must be greater than or equal to 64 characters long., The 'senderPublicKey' field fails to match the required pattern."
    }

      20 | 	if (error.response) {
      21 | 		if (error.response.status !== expectedStatusCode) {
    > 22 | 			throw new Error(`Status code: ${error.response.status}
         | 			      ^
      23 | 			\n${JSON.stringify(error.response.data, null, 2)}`);
      24 | 		}
      25 | 		return error.response.data;

      at handleError (helpers/api.js:22:10)
      at helpers/api.js:39:19
```

**Comment by nagdahimanshu** [comment]
Closing this issue as it no longer exists. All relevant tests (`Fix transaction retrieval by public key (tests)`) has been enabled with the PR https://github.com/LiskHQ/lisk-service/pull/771 and are passing consistently on `Jenkins`
