### ISSUE TITLE
Unlock transaction not getting through

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/lisk-service#742]
### Actual behavior
A user reported broadcasting an `unlock` transaction as being not successful. It fails even after multiple attempts.

The following error was reported via email:
```
Important metadata for the team, please do not edit:

{"error":{"code":400},"transaction":{"moduleID":5,"assetID":2,"senderPublicKey":"b7fdfc991c52ad6646159506a8326d4203c868bd3f16b8043c8e4e034346e581","nonce":"4n","fee":"220000n","signatures":["d0cc23842b0f8e967462a567babf6eafce8aa025178c0f71e8416ea46f47c14c088f992a33bd94687274e1e60c9a455511aaf988b359cc52a4851d78f5e75c0a"],"asset":{"unlockObjects":[{"amount":"700000000000n","delegateAddress":"4cd2d0abb4f329fc758a844b458bb295306cd6b9","unvoteHeight":16342421},{"amount":"3000000000000n","delegateAddress":"b7f2f72457092c57925d9431973f87ae6f57c618","unvoteHeight":16342421},{"amount":"2000000000000n","delegateAddress":"b7f2f72457092c57925d9431973f87ae6f57c618","unvoteHeight":16332862}]},"id":"2d00ab402e444a05e4629dc4e4d64d04fe69883fa09590c63e3410eef1307775"}}
```
![image](https://user-images.githubusercontent.com/21265252/131972550-561a5bd2-2099-4486-b325-10f411057dc9.png)

### Expected behavior
The transaction should be successfully broadcast to the network

### Steps to reproduce
--

### Which version(s) does this affect? (Environment, OS, etc...)

Lisk Desktop `2.0.0` and Lisk Service `0.4.4` (Mainnet)

**Comment by sameersubudhi** [comment]
This error could be generated by the Lisk SDK elements within the Lisk Desktop when it tries to sign the transaction. It could be most likely due to assigning `"amount":"700000000000n"`  instead of `"amount":"700000000000"`, `"amount":700000000000` or `"amount":700000000000n`.

```
This could be verified on the command line:

Sameers-MacBook-Pro:~ sameer$ lisk-core transaction:create 5 2 220000 --asset='{"unlockObjects":[{"amount":"700000000000n","delegateAddress":"4cd2d0abb4f329fc758a844b458bb295306cd6b9","unvoteHeight":16342421},{"amount":"3000000000000n","delegateAddress":"b7f2f72457092c57925d9431973f87ae6f57c618","unvoteHeight":16342421},{"amount":"2000000000000n","delegateAddress":"b7f2f72457092c57925d9431973f87ae6f57c618","unvoteHeight":16332862}]}' -d ~/mainnet
 ›   Error: Cannot convert 700000000000n to a BigInt

==============================================

Sameers-MacBook-Pro:~ sameer$ lisk-core transaction:create 5 2 220000 --asset='{"unlockObjects":[{"amount":"700000000000","delegateAddress":"4cd2d0abb4f329fc758a844b458bb295306cd6b9","unvoteHeight":16342421},{"amount":"3000000000000","delegateAddress":"b7f2f72457092c57925d9431973f87ae6f57c618","unvoteHeight":16342421},{"amount":"2000000000000","delegateAddress":"b7f2f72457092c57925d9431973f87ae6f57c618","unvoteHeight":16332862}]}' -d ~/mainnet
? Please enter passphrase:  [input is hidden] 
Sameers-MacBook-Pro:~ sameer$
```

**Comment by przemerr** [comment]
https://github.com/LiskHQ/lisk-desktop/issues/3767
this is the reason

**Comment by sameersubudhi** [comment]
@przemerr This issue seems unrelated as the account here doesn't have a PoM https://service.lisk.io/api/v2/accounts?publicKey=b7fdfc991c52ad6646159506a8326d4203c868bd3f16b8043c8e4e034346e581

**Comment by przemerr** [comment]
@sameersubudhi this delegate  `b7f2f72457092c57925d9431973f87ae6f57c618` has

**Comment by sameersubudhi** [comment]
As @przemerr states, this issue is related to incorrect unlocking heights calculation and should be fixed by https://github.com/LiskHQ/lisk-service/issues/735.
