### ISSUE TITLE
Fix delegate rank calculation

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#782]
### Actual behavior

Delegate rank is inconsistent across deployments (testnet-service vs localhost).

Possibly it depends on the operating system (MacOS vs Linux).

That issue was similar to the fee estimator discrepancies.

### Expected behavior

Local and server deployments return consistent results.

### Steps to reproduce

Retrieve delegate list.

**Comment by nagdahimanshu** [comment]
This issue is invalid. Hence, closing the issue!
