### ISSUE TITLE
Missing fields on /accounts, random behaviour

### ISSUE THREAD

**Issue by dakk** [LiskHQ/lisk-service#796]
### Actual behavior
When I call ```https://service.lisk.io/api/v2/accounts?username=anamix``` sometimes I get this result, which doesn't include the rewards and producedBlocks fields:
```js 
{'username': 'anamix', 'consecutiveMissedBlocks': 0, 'lastForgedHeight': 16585979, 'isBanned': False, 'voteWeight': '18759000000000', 'totalVotesReceived': '18759000000000', 'rank': 39}
```

### Expected behavior

While sometimes I get it correct: 
```js 
{'username': 'anamix', 'consecutiveMissedBlocks': 0, 'registrationHeight': False, 'lastForgedHeight': 16585979, 'isBanned': False, 'voteWeight': '18759000000000', 'totalVotesReceived': '18759000000000', 'producedBlocks': 1785, 'rank': 39, 'rewards': '178300000000'}
```

### Steps to reproduce
It is random, sometimes it's wrong, sometimes it's correct.

**Comment by przemerr** [comment]
Yes, it's because of the load balancing and different instances of Lisk Service giving different responses. https://github.com/LiskHQ/lisk-service/issues/772
this should fix the issue

**Comment by sameersubudhi** [comment]
@dakk The fields `producedBlocks` and `rewards` within the response are returned only when the following conditions are met:
- Lisk Service is started with `INDEX_N_BLOCK: 0` i.e. complete blockchain indexing mode enabled
- There are no missing entries within the 'blocks' index after Lisk Service finishes the indexing process

And, as @przemerr stated above we're currently working on the atomicity issue to correctly calculate the `producedBlocks` and `rewards` values consistently (https://github.com/LiskHQ/lisk-service/issues/772)

Kindly let us know if there are any other issues else we'll be closing the issue in a while.

**Note**: To ensure that the missing entries within the 'blocks' index are updated, consider enabling the `missingBlocks` job with the following environment variables: `ENABLE_JOB_MISSING_BLOCKS: true` and `INDEX_MISSING_BLOCKS_RANGE: 0`

**Comment by dakk** [comment]
> @dakk The fields `producedBlocks` and `rewards` within the response are returned only when the following conditions are met:
> 
>     * Lisk Service is started with `INDEX_N_BLOCK: 0` i.e. complete blockchain indexing mode enabled
> 
>     * There are no missing entries within the 'blocks' index after Lisk Service finishes the indexing process
> 
> 
> And, as @przemerr stated above we're currently working on the atomicity issue to correctly calculate the `producedBlocks` and `rewards` values consistently (#772)
> 
> Kindly let us know if there are any other issues else we'll be closing the issue in a while.

Ok fine, thank you for the clarification. 

Duplicate of #772
