### ISSUE TITLE
Add totalLocked, totalStaked and totalSelfStaked into API

### ISSUE THREAD

**Issue by Suepaphly** [LiskHQ/lisk-service#797]
### Description

Similar to how producedBlocks is provided for delegates, it would also make sense to provide the totalLiskSupply and the totalLockedLisk into the API for /api/v2/network/statistics. 

### Motivation

Drastically reduces the amount of API calls that are required to get these numbers.

**Comment by Suepaphly** [comment]
I think splitting them into totalVoted and totalSelfVoted would be better, now that I've thought a little more about it.

**Comment by MichalTuleja** [comment]
That feature needs to be discussed across the team first.

To make the implementation the Lisk SDK needs to provide them by the API, otherwise things get a little complicated. 

@shuse2 Are these properties calculated by the Lisk SDK modules?
