### ISSUE TITLE
Return vote `timestamp` and `transactionId` in /v2/votes_received

### ISSUE THREAD

**Issue by corbifex** [LiskHQ/lisk-service#798]
### Actual behavior
`/api/v2/votes_received` doesn't return timestamp and transactionId of when a vote took place
[/api/v2/votes_received](https://service.lisk.com/api/v2/votes_received?username=moosty)
it returns:
```json
[{
"address": "lskfgeepfjw99398dyqwdtha6m9uoc3g7eh3uqyop",
"amount": "-576000000000"
}]
```
### Expected behavior
It should return it with timestamp and transactionId:
```json
[{
"address": "lskfgeepfjw99398dyqwdtha6m9uoc3g7eh3uqyop",
"amount": "-576000000000",
"timestamp": 1632974780,
"transactionId": "bab5748cf56c47cd8d947b6107decc16b5224ffbc9473e5fd7f85a33edff8675"
}]
```

**Comment by sameersubudhi** [comment]
Since this doesn't apply to future releases, closing the issue.
