### ISSUE TITLE
Improve regression tests

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#808]
### Description

Please address the issues mentioned in #779

- Some account properties are fixed and need to be strictly checked
- Some properties are constantly changing (i.e. balance) and require only a numerical string presence
- Tests should not strictly test the number of properties, so tests will not fail on new properties

### Acceptance Criteria

- Tests are deterministic (ranges applied when value is changing)
- Strict type checking
- Normalize `expect()` and `strictEqual()` so new (untested) properties are passing

**Comment by sameersubudhi** [comment]
The regression tests will now be outdated with the v0.7.0 release and the above changes won't be necessary. New regression tests will be created for the future patch releases.
