### ISSUE TITLE
Double log entries in PM2

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-service#827]
### Actual behavior
The log entries in pm2 are always shown twice.

My logging settings in `ecosystem.core3.config.js` for the lisk service core module:
```
SERVICE_LOG_STDOUT: true,
SERVICE_LOG_LEVEL: 'info',
SERVICE_LOG_CONSOLE: true
```

![image](https://user-images.githubusercontent.com/1260700/138246223-7e95a122-ecda-417b-9cff-c65312e7f60b.png)

![image](https://user-images.githubusercontent.com/1260700/138245726-0b894813-9c07-4dec-967d-ad41e05c4c96.png)

### Expected behavior
It should not show every entry twice.

### Steps to reproduce
Run a Lisk Service node on version 0.5.0-beta.0

### Which version(s) does this affect? (Environment, OS, etc...)
Ubuntu 20.04.3 LTS
nvm: 0.38.0 
npm: 6.14.15
node: v12.22.7

**Comment by MichalTuleja** [comment]
Hello @punkrock ,

In that case `SERVICE_LOG_STDOUT` and `SERVICE_LOG_CONSOLE` should be enabled exclusively instead of enabling both of them. The `SERVICE_LOG_STDOUT` is the recommended method of using the logging capabilities.
