### ISSUE TITLE
Create Jenkinsfile for weekly mainnet tests

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#845]
### Description

Create Jenkinsfile that runs Lisk Service against mainnet and triggers full indexing.

Create another Jenkinsfile that runs **regression** tests on the full blockchain index. 

Create another Jenkinsfile that runs **performance** tests on the full blockchain index. 

### Acceptance Criteria

- Every week a new deployment is done
- Regression tests are performed
- Development branch is used

**Comment by ManuGowda** [comment]
@nagdahimanshu will work with devops team to run the jobs that be created.
