### ISSUE TITLE
Indexer microservice tracks syncing status

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#872]
### Description

Make indexer microservice track the syncing status.

### Acceptance Criteria

- The Lisk SDK- based blockchain application's node status can be retrieved from the node info - the app makes use of that.
- Lisk Service does not attempt indexing until the syncing is done
- The queue needs to be paused when syncing is `true`
- The queue resumes when syncing is `false`
- The `newBlock` event should not be triggered/processed instantly during the node synchronization

**Comment by sameersubudhi** [comment]
Bull Queue doesn't let us pause the job queue. So, can be marked invalid and closed for now.
