### ISSUE TITLE
Indicate in API response when there are no delegates that fulfil minimum vote weight to be eligible as standby

### ISSUE THREAD

**Issue by isalga** [LiskHQ/lisk-service#889]
### Description

Supply a specific error or response (empty array) that indicates when there are no delegates that fulfil minimum vote weight to be standby.

### Motivation

Currently API returns 404 when there are no delegates with voteWeight over 1000 LSK to be eligible as standby on this call (https://testnet-service.lisk.com/api/v2/accounts?isDelegate=true&limit=20&status=standby). As Desktop team plans to display a label that indicates no standby delegates were found instead of a general 'nothing found'. For that desktop needs a specific way of indicating that case instead of a 404

### Additional Information

 @https://github.com/liskhq/lisk-desktop/issues/3948

**Comment by reyraa** [comment]
Duplicate of #888
