### ISSUE TITLE
'votes_received' endpoint returns different data across Lisk Services

### ISSUE THREAD

**Issue by nerdvibe** [LiskHQ/lisk-service#921]
### Actual behavior

It appears that service.lisk.com and mainnet-service.lisktools.eu return two different arrays of voters. It seems like service.lisk.com is wrong and mainnet-service.lisktools.eu to be correct.

```
"meta": {
    "count": 62,
    "offset": 0,
    "total": 62
  }
https://service.lisk.com/api/v2/votes_received?username=carbonara&aggregate=true&limit=100&offset=0
```
```
"meta": {
    "count": 61,
    "offset": 0,
    "total": 61
  }
https://mainnet-service.lisktools.eu/api/v2/votes_received?username=carbonara&aggregate=true&limit=100&offset=0
```

The extra address seems to be at least `lskm7dquz6jepotwx4z4uyt2oswaaphdyz98nzy7c`. If I'm not wrong, there is at least another address from another delegate affected from this issue.

### Expected behavior

Probably the right data is from mainnet-service.lisktools.eu

### Steps to reproduce
see above.

### Which version(s) does this affect? (Environment, OS, etc...)
API - version unknown.

**Comment by ManuGowda** [comment]
@nerdvibe I tried to test the endpoints you provided, they seem to return similar results
 
<img width="893" alt="Screenshot 2021-12-26 at 5 26 56 PM" src="https://user-images.githubusercontent.com/6449871/147414312-f7e05c00-20bf-4b98-a379-412200457e79.png">
<img width="798" alt="Screenshot 2021-12-26 at 5 27 07 PM" src="https://user-images.githubusercontent.com/6449871/147414313-9bf61c20-e96d-4760-9539-9c11bdf19324.png">

**Comment by nerdvibe** [comment]
![image](https://user-images.githubusercontent.com/6796782/147414779-fed4da03-7b1b-4a53-9be8-fd16c53bf9a2.png)
![image](https://user-images.githubusercontent.com/6796782/147414785-b35f0b3f-66d0-43db-9a72-e8b10cb3058c.png)

O.O to me issue is still showing...

**Comment by nerdvibe** [comment]
Update, I tried in incognito and now the results are the same, I suspect that in this case it might have been some browser caching issue.

Anyway, I have the suspect that there is an issue somewhere, because our payout script picked up a non-voting address (and paid it out 😅). The same happened to `liskmagazine` where they also picked the same non voting address and paid out to them (we have different scripts).

The non voting address was `lskm7dquz6jepotwx4z4uyt2oswaaphdyz98nzy7c`. Maybe something useful for the investigations, the mentioned address voted for both of us in the past (for `carbonara` I'm sure, for `liskmagazine` iirc too).

**Comment by przemerr** [comment]
there's definitely an issue, just keep pooling the query with intervals of 2 seconds, you will get different results every X polls, applies to `https://service.lisk.com/api/v2/votes_received?username=carbonara&aggregate=true&limit=1` and `liskmagazine`, probably some lisk-service instances used for load balancing have wrong data.

**Comment by ManuGowda** [comment]
@nagdahimanshu please take a look into this.
